name: Showcase
on:
  push:
    branches:
      - master
env:
  SHOWCASE_ENV: lol
jobs:
  build:
    name: TODO
    runs-on: ubuntu-latest
    steps:
      - id: command
        run: echo ${{ env.SHOWCASE_ENV }}
      - id: show_pipeline_environemnt
        run: ls
        name: sanya
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: my-branch
      - run: git checkout HEAD^
      